In [33]:
# Import the libraries.
import requests
import json
import gmaps
import pandas as pd
# Import the API keys.
from config import weather_api_key
from config import g_key

In [34]:
top_50 = pd.read_csv("top50.csv")
top_50.head()

          City       State
0     New York    New York
1  Los Angeles  California
2      Chicago    Illinois
3      Houston       Texas
4      Phoenix     Arizona

In [35]:
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&appid=" + weather_api_key
cities = top_50["City"]



print(cities)

0             New York
1          Los Angeles
2              Chicago
3              Houston
4              Phoenix
5         Philadelphia
6          San Antonio
7            San Diego
8               Dallas
9             San Jose
10              Austin
11        Jacksonville
12          Fort Worth
13            Columbus
14           Charlotte
15       San Francisco
16        Indianapolis
17             Seattle
18              Denver
19          Washington
20              Boston
21             El Paso
22           Nashville
23             Detroit
24            Oklahoma
25            Portland
26           Las Vegas
27             Memphis
28          Louisville
29           Baltimore
30           Milwaukee
31         Albuquerque
32              Tucson
33              Fresno
34                Mesa
35          Sacramento
36             Atlanta
37              Kansas
38    Colorado Springs
39               Omaha
40             Raleigh
41               Miami
42          Long Beach
43      Virginia Beach
44             Oakland
45         Minneapolis
46               Tulsa
47               Tampa
48           Arlington
49         New Orleans
Name: City, dtype: object

In [40]:
city_data = []

for city in cities:
    city_url = url + "&q=" + city.replace(" ","+")
    city_weather = requests.get(city_url).json()
    city_lat = city_weather["coord"]["lat"]
    city_lng = city_weather["coord"]["lon"]
    city_max_temp = city_weather["main"]["temp_max"]
    city_humidity = city_weather["main"]["humidity"]
    city_desc = city_weather["weather"][0]["description"]
    city_data.append({"Lat":city_lat,
                     "Lng": city_lng,
                     "Max Temp": city_max_temp,
                     "Humidity": city_humidity,
                     "Description": city_desc})

In [41]:
city_data_df = pd.DataFrame(city_data)
city_data_df

        Lat       Lng  Max Temp  Humidity       Description
0   40.7143  -74.0060     76.24        66   overcast clouds
1   34.0522 -118.2437    109.76        42         clear sky
2   41.8500  -87.6500     94.71        54  scattered clouds
3   29.7633  -95.3633     92.32        72      thunderstorm
4   33.4484 -112.0740    106.63        27     broken clouds
5   39.9523  -75.1638     75.87        85   overcast clouds
6   29.4241  -98.4936     93.29        61     broken clouds
7   32.7153 -117.1573    106.27        70  scattered clouds
8   32.7668  -96.7836     96.49        53  scattered clouds
9   37.3394 -121.8950    104.90        24              haze
10  30.2672  -97.7431     95.36        55  scattered clouds
11  30.3322  -81.6556     90.01        76              haze
12  32.7254  -97.3208     95.72        53  scattered clouds
13  39.9612  -82.9988     92.70        61  scattered clouds
14  35.2271  -80.8431     95.09        50        few clouds
15  37.7749 -122.4194    102.65        41              haze
16  39.7684  -86.1580     91.74        58     broken clouds
17  47.6062 -122.3321     78.08        58         clear sky
18  39.7392 -104.9847     96.67        23         clear sky
19  47.5001 -120.5015     80.47        28     broken clouds
20  42.3584  -71.0598     70.45        70   overcast clouds
21  31.8001 -106.2005     93.13        29         clear sky
22  36.1659  -86.7844     91.71        55     broken clouds
23  42.3314  -83.0458     94.06        61  scattered clouds
24  35.5501  -97.4003     95.72        44        few clouds
25  45.5234 -122.6762     85.10        45        few clouds
26  36.1750 -115.1372    108.61        12         clear sky
27  35.1495  -90.0490     96.15        49     broken clouds
28  38.2542  -85.7594     95.25        50     broken clouds
29  39.2904  -76.6122     92.82        77     broken clouds
30  43.0006  -87.9668     95.22        55      thunderstorm
31  35.0845 -106.6511     92.41        29  scattered clouds
32  32.2217 -110.9265    104.58        30         clear sky
33  36.6666 -119.8343    105.94        23              haze
34  33.4223 -111.8226    106.66        28         clear sky
35  38.4666 -121.3177    102.49        22              haze
36  33.7490  -84.3880     90.75        59     broken clouds
37  38.5003  -98.5006     97.07        27        few clouds
38  38.8339 -104.8214     96.42        15  scattered clouds
39  41.2586  -95.9378     94.15        50  scattered clouds
40  35.7721  -78.6386     97.72        55  scattered clouds
41  25.7743  -80.1937     91.42        70     broken clouds
42  33.7670 -118.1892    107.73        65              haze
43  36.8529  -75.9780     94.03        62  scattered clouds
44  42.6667  -83.3999     92.75        62     broken clouds
45  44.9800  -93.2638     85.33        59     broken clouds
46  36.1001  -95.9003     93.63        52  scattered clouds
47  27.9475  -82.4584     92.71        68   overcast clouds
48  32.7357  -97.1081     95.52        50         clear sky
49  29.9547  -90.0751     88.09        72        few clouds

In [42]:
cities_df = pd.concat([top_50, city_data_df], axis = 1, ignore_index=True)
cities_df.columns=["city","state","lat","lng","temp","humidity","desc"]
cities_df

,city,state,lat,lng,temp,humidity,desc
0,New York,New York,40.7143,-74.0060,76.24,66,overcast clouds
1,Los Angeles,California,34.0522,-118.2437,109.76,42,clear sky
2,Chicago,Illinois,41.8500,-87.6500,94.71,54,scattered clouds
3,Houston,Texas,29.7633,-95.3633,92.32,72,thunderstorm
4,Phoenix,Arizona,33.4484,-112.0740,106.63,27,broken clouds
5,Philadelphia,Pennsylvania,39.9523,-75.1638,75.87,85,overcast clouds
6,San Antonio,Texas,29.4241,-98.4936,93.29,61,broken clouds
7,San Diego,California,32.7153,-117.1573,106.27,70,scattered clouds
8,Dallas,Texas,32.7668,-96.7836,96.49,53,scattered clouds
9,San Jose,California,37.3394,-121.8950,104.90,24,haze
10,Austin,Texas,30.2672,-97.7431,95.36,55,scattered clouds
11,Jacksonville,Florida,30.3322,-81.6556,90.01,76,haze
12,Fort Worth,Texas,32.7254,-97.3208,95.72,53,scattered clouds
13,Columbus,Ohio,39.9612,-82.9988,92.70,61,scattered clouds
14,Charlotte,North Carolina,35.2271,-80.8431,95.09,50,few clouds
15,San Francisco,California,37.7749,-122.4194,102.65,41,haze
16,Indianapolis,Indiana,39.7684,-86.1580,91.74,58,broken clouds
17,Seattle,Washington,47.6062,-122.3321,78.08,58,clear sky
18,Denver,Colorado,39.7392,-104.9847,96.67,23,clear sky
19,Washington,District of Columbia,47.5001,-120.5015,80.47,28,broken clouds
20,Boston,Massachusetts,42.3584,-71.0598,70.45,70,overcast clouds
21,El Paso,Texas,31.8001,-106.2005,93.13,29,clear sky
22,Nashville,Tennessee,36.1659,-86.7844,91.71,55,broken clouds
23,Detroit,Michigan,42.3314,-83.0458,94.06,61,scattered clouds
24,Oklahoma,Oklahoma,35.5501,-97.4003,95.72,44,few clouds
25,Portland,Oregon,45.5234,-122.6762,85.10,45,few clouds
26,Las Vegas,Nevada,36.1750,-115.1372,108.61,12,clear sky
27,Memphis,Tennessee,35.1495,-90.0490,96.15,49,broken clouds
28,Louisville,Kentucky,38.2542,-85.7594,95.25,50,broken clouds
29,Baltimore,Maryland,39.2904,-76.6122,92.82,77,broken clouds
30,Milwaukee,Wisconsin,43.0006,-87.9668,95.22,55,thunderstorm
31,Albuquerque,New Mexico,35.0845,-106.6511,92.41,29,scattered clouds
32,Tucson,Arizona,32.2217,-110.9265,104.58,30,clear sky
33,Fresno,California,36.6666,-119.8343,105.94,23,haze
34,Mesa,Arizona,33.4223,-111.8226,106.66,28,clear sky
35,Sacramento,California,38.4666,-121.3177,102.49,22,haze
36,Atlanta,Georgia,33.7490,-84.3880,90.75,59,broken clouds
37,Kansas,Missouri,38.5003,-98.5006,97.07,27,few clouds
38,Colorado Springs,Colorado,38.8339,-104.8214,96.42,15,scattered clouds
39,Omaha,Nebraska,41.2586,-95.9378,94.15,50,scattered clouds
40,Raleigh,North Carolina,35.7721,-78.6386,97.72,55,scattered clouds
41,Miami,Florida,25.7743,-80.1937,91.42,70,broken clouds
42,Long Beach,California,33.7670,-118.1892,107.73,65,haze
43,Virginia Beach,Virginia,36.8529,-75.9780,94.03,62,scattered clouds
44,Oakland,California,42.6667,-83.3999,92.75,62,broken clouds
45,Minneapolis,Minnesota,44.9800,-93.2638,85.33,59,broken clouds
46,Tulsa,Oklahoma,36.1001,-95.9003,93.63,52,scattered clouds
47,Tampa,Florida,27.9475,-82.4584,92.71,68,overcast clouds
48,Arlington,Texas,32.7357,-97.1081,95.52,50,clear sky
49,New Orleans,Louisiana,29.9547,-90.0751,88.09,72,few clouds

In [44]:
info_box_template = """
<dl>
<dt>City</dt><dd>{city}</dd>
<dt>Current Weather</dt><dd>{desc} and {temp} °F</dd>
</dl>
"""

locations = cities_df[["lat","lng"]]

weather_info = [info_box_template.format(**row) for index, row in cities_df.iterrows()]

In [45]:
marker_layer = gmaps.marker_layer(locations, info_box_content=weather_info)

fig = gmaps.figure(center=(100.0, 100.0), zoom_level=1.5)

fig.add_layer(marker_layer)

In [49]:
fig

Figure(layout=FigureLayout(height='420px'))